#!/usr/bin/env python3
import argparse
import json
import pathlib


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_features(root: pathlib.Path):
    features = []
    for path in sorted(root.rglob("feature.json")):
        data = json.loads(path.read_text())
        data["_path"] = path
        features.append(data)
    return features


def emit_string_array(out, name, values):
    if not values:
        out.write(f"static const char * const {name}[] = {{ 0 }};\n")
        return
    out.write(f"static const char * const {name}[] = {{\n")
    for value in values:
        out.write(f"    {c_string(value)},\n")
    out.write("};\n")


def symbol_for(feature_id, suffix):
    safe = "".join(ch if ch.isalnum() else "_" for ch in feature_id)
    return f"pie_feature_{safe}_{suffix}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--out-c", required=True)
    parser.add_argument("--out-h", required=True)
    args = parser.parse_args()

    root = pathlib.Path(args.root)
    out_c = pathlib.Path(args.out_c)
    out_h = pathlib.Path(args.out_h)
    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_h.parent.mkdir(parents=True, exist_ok=True)
    features = load_features(root)

    out_h.write_text(
        "/* Auto-generated by tools/generators/gen_registry.py. Do not edit. */\n"
        "#ifndef PIE_FEATURE_REGISTRY_GENERATED_H\n"
        "#define PIE_FEATURE_REGISTRY_GENERATED_H\n\n"
        "#include \"pie/core/registry/registry.h\"\n\n"
        "const PieFeatureRegistry *pie_feature_registry_generated(void);\n\n"
        "#endif\n"
    )

    with out_c.open("w") as out:
        out.write("/* Auto-generated by tools/generators/gen_registry.py. Do not edit. */\n")
        out.write("#include \"feature_registry.generated.h\"\n\n")
        for feature in features:
            for field in ("deps", "tokens", "keywords", "operators", "ast_nodes", "type_kinds", "hooks"):
                emit_string_array(out, symbol_for(feature["id"], field), feature[field])
            out.write("\n")

        out.write("static const PieFeature pie_generated_features[] = {\n")
        for feature in features:
            out.write("    {\n")
            out.write(f"        .id = {c_string(feature['id'])},\n")
            out.write(f"        .name = {c_string(feature['name'])},\n")
            out.write(f"        .group = {c_string(feature['group'])},\n")
            out.write(f"        .version = {c_string(feature['version'])},\n")
            out.write(f"        .kind = {c_string(feature['kind'])},\n")
            for field in ("deps", "tokens", "keywords", "operators", "ast_nodes", "type_kinds", "hooks"):
                out.write(f"        .{field} = {symbol_for(feature['id'], field)},\n")
                singular = field[:-1] if field.endswith("s") else field
                if field == "type_kinds":
                    count_field = "type_kind_count"
                elif field == "ast_nodes":
                    count_field = "ast_node_count"
                else:
                    count_field = f"{singular}_count"
                out.write(f"        .{count_field} = {len(feature[field])},\n")
            out.write("    },\n")
        out.write("};\n\n")
        out.write("const PieFeatureRegistry *pie_feature_registry_generated(void) {\n")
        out.write("    static const PieFeatureRegistry registry = {\n")
        out.write("        .features = pie_generated_features,\n")
        out.write(f"        .count = {len(features)},\n")
        out.write("    };\n")
        out.write("    return &registry;\n")
        out.write("}\n")


if __name__ == "__main__":
    main()
