#!/usr/bin/env python3
import argparse
import json
import pathlib


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_features(root: pathlib.Path):
    features = []
    for path in sorted(root.rglob("feature.json")):
        data = json.loads(path.read_text())
        data["_path"] = str(path)
        features.append(data)
    return features


def parse_hooks(feature):
    hooks = feature.get("parse_hooks", {})
    return (
        hooks.get("top_level", []),
        hooks.get("stmt", []),
        hooks.get("expr_prefix", []),
        hooks.get("expr_infix", []),
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--out-c", required=True)
    args = parser.parse_args()

    features = load_features(pathlib.Path(args.root))
    out_c = pathlib.Path(args.out_c)
    out_c.parent.mkdir(parents=True, exist_ok=True)

    top_level = []
    stmt = []
    expr_prefix = []
    expr_infix = []
    for feature in features:
        top_hooks, stmt_hooks, prefix_hooks, infix_hooks = parse_hooks(feature)
        for hook in top_hooks:
            top_level.append((feature["id"], hook))
        for hook in stmt_hooks:
            stmt.append((feature["id"], hook))
        for hook in prefix_hooks:
            expr_prefix.append((feature["id"], hook))
        for hook in infix_hooks:
            expr_infix.append((feature["id"], hook))

    with out_c.open("w") as out:
        out.write("/* Auto-generated by tools/generators/gen_parse_hooks.py. Do not edit. */\n")
        out.write("#include \"pie/core/parser/parser.h\"\n\n")

        for _, hook in top_level:
            out.write(f"PieParseResult {hook}(PieParseContext *ctx, PieProgram *program);\n")
        for _, hook in stmt:
            out.write(f"PieParseResult {hook}(PieParseContext *ctx, PieProgram *program);\n")
        for _, hook in expr_prefix:
            out.write(f"PieParseResult {hook}(PieParseContext *ctx, PieExpr **out_expr);\n")
        for _, hook in expr_infix:
            out.write(f"PieParseResult {hook}(PieParseContext *ctx, PieExpr **left, int min_precedence);\n")
        out.write("\n")

        out.write("static const PieTopLevelParseHook PIE_TOP_LEVEL_HOOKS[] = {\n")
        for feature_id, hook in top_level:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")

        out.write("static const PieStmtParseHook PIE_STMT_HOOKS[] = {\n")
        for feature_id, hook in stmt:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")

        out.write("static const PieExprPrefixParseHook PIE_EXPR_PREFIX_HOOKS[] = {\n")
        for feature_id, hook in reversed(expr_prefix):
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")

        out.write("static const PieExprInfixParseHook PIE_EXPR_INFIX_HOOKS[] = {\n")
        for feature_id, hook in expr_infix:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")

        out.write("const PieParseHookRegistry *pie_parse_hook_registry(void) {\n")
        out.write("    static const PieParseHookRegistry registry = {\n")
        out.write("        .top_level_hooks = PIE_TOP_LEVEL_HOOKS,\n")
        out.write(f"        .top_level_hook_count = {len(top_level)},\n")
        out.write("        .stmt_hooks = PIE_STMT_HOOKS,\n")
        out.write(f"        .stmt_hook_count = {len(stmt)},\n")
        out.write("        .expr_prefix_hooks = PIE_EXPR_PREFIX_HOOKS,\n")
        out.write(f"        .expr_prefix_hook_count = {len(expr_prefix)},\n")
        out.write("        .expr_infix_hooks = PIE_EXPR_INFIX_HOOKS,\n")
        out.write(f"        .expr_infix_hook_count = {len(expr_infix)},\n")
        out.write("    };\n")
        out.write("    return &registry;\n")
        out.write("}\n")


if __name__ == "__main__":
    main()
