#!/usr/bin/env python3
import argparse
import json
import pathlib


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--out-c", required=True)
    args = parser.parse_args()

    stmt_hooks = []
    expr_hooks = []
    for path in sorted(pathlib.Path(args.root).rglob("feature.json")):
        data = json.loads(path.read_text())
        for hook in data.get("lower_hooks", {}).get("stmt", []):
            stmt_hooks.append((data["id"], hook))
        for hook in data.get("lower_hooks", {}).get("expr", []):
            expr_hooks.append((data["id"], hook))

    out_c = pathlib.Path(args.out_c)
    out_c.parent.mkdir(parents=True, exist_ok=True)
    with out_c.open("w") as out:
        out.write("/* Auto-generated by tools/generators/gen_lower_hooks.py. Do not edit. */\n")
        out.write("#include \"pie/core/lower/lower.h\"\n\n")
        for _, hook in stmt_hooks:
            out.write(f"PieLowerResult {hook}(PieLowerContext *ctx, const PieStmt *stmt);\n")
        for _, hook in expr_hooks:
            out.write(f"PieLowerResult {hook}(PieLowerContext *ctx, const PieExpr *expr, PieIrExpr **out_expr);\n")
        out.write("\n")
        out.write("static const PieLowerStmtHook PIE_LOWER_STMT_HOOKS[] = {\n")
        for feature_id, hook in stmt_hooks:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")
        out.write("static const PieLowerExprHook PIE_LOWER_EXPR_HOOKS[] = {\n")
        for feature_id, hook in expr_hooks:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")
        out.write("const PieLowerHookRegistry *pie_lower_hook_registry(void) {\n")
        out.write("    static const PieLowerHookRegistry registry = {\n")
        out.write("        .stmt_hooks = PIE_LOWER_STMT_HOOKS,\n")
        out.write(f"        .stmt_hook_count = {len(stmt_hooks)},\n")
        out.write("        .expr_hooks = PIE_LOWER_EXPR_HOOKS,\n")
        out.write(f"        .expr_hook_count = {len(expr_hooks)},\n")
        out.write("    };\n")
        out.write("    return &registry;\n")
        out.write("}\n")


if __name__ == "__main__":
    main()
