#!/usr/bin/env python3
import argparse
import json
import pathlib


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--out-c", required=True)
    args = parser.parse_args()

    stmt_hooks = []
    expr_hooks = []
    for path in sorted(pathlib.Path(args.root).rglob("feature.json")):
        data = json.loads(path.read_text())
        for hook in data.get("asm_hooks", {}).get("stmt", []):
            stmt_hooks.append((data["id"], hook))
        for hook in data.get("asm_hooks", {}).get("expr", []):
            expr_hooks.append((data["id"], hook))

    out_c = pathlib.Path(args.out_c)
    out_c.parent.mkdir(parents=True, exist_ok=True)
    with out_c.open("w") as out:
        out.write("/* Auto-generated by tools/generators/gen_asm_hooks.py. Do not edit. */\n")
        out.write("#include \"pie/backend/asm/asm_codegen.h\"\n\n")
        for _, hook in stmt_hooks:
            out.write(f"PieAsmGenResult {hook}(PieAsmCodegenContext *ctx, const PieIrStmt *stmt);\n")
        for _, hook in expr_hooks:
            out.write(f"PieAsmGenResult {hook}(PieAsmCodegenContext *ctx, const PieIrExpr *expr);\n")
        out.write("\n")
        out.write("static const PieAsmStmtGenHook PIE_ASM_STMT_HOOKS[] = {\n")
        for feature_id, hook in stmt_hooks:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")
        out.write("static const PieAsmExprGenHook PIE_ASM_EXPR_HOOKS[] = {\n")
        for feature_id, hook in expr_hooks:
            out.write(f"    {{{c_string(feature_id)}, {hook}}},\n")
        out.write("};\n\n")
        out.write("const PieAsmHookRegistry *pie_asm_hook_registry(void) {\n")
        out.write("    static const PieAsmHookRegistry registry = {\n")
        out.write("        .stmt_hooks = PIE_ASM_STMT_HOOKS,\n")
        out.write(f"        .stmt_hook_count = {len(stmt_hooks)},\n")
        out.write("        .expr_hooks = PIE_ASM_EXPR_HOOKS,\n")
        out.write(f"        .expr_hook_count = {len(expr_hooks)},\n")
        out.write("    };\n")
        out.write("    return &registry;\n")
        out.write("}\n")


if __name__ == "__main__":
    main()
